ARG NOTEBOOK_TAG=latest
FROM quay.io/jupyter/minimal-notebook:${NOTEBOOK_TAG}

RUN set -eux \
    && useradd -m -d /home/user01 user01 \
    && apt-get update && apt-get install -y --no-install-recommends \
    ghostscript \
    imagemagick \
    && rm -rf /var/lib/apt/lists/* \
    && mv /etc/ImageMagick-6/policy.xml /etc/ImageMagick-6/policy.xmlout

USER user01
WORKDIR /home/user01/
