FROM mysql:9.7

# A failed download in a curl | mysql pipeline must fail the build.
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ENV MYSQL_ALLOW_EMPTY_PASSWORD=1 \
    PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN set -eux \
    && useradd -m -d /home/user01 user01 \
    && microdnf install -y \
    time \
    && microdnf clean all \
    && mysqld --initialize-insecure \
    && mysqld --daemonize \
    && while ! mysqladmin ping --silent; do sleep 1; done \
    && curl -fsSL https://raw.githubusercontent.com/harryho/db-samples/master/mysql/northwind.sql | sed 's|,PRIMARY KEY (orderId,custId)|,PRIMARY KEY (orderId,custId),UNIQUE (orderId)|' | mysql \
    && mysql -e 'CREATE DATABASE wikipedia' \
    && curl -fsSL https://raw.githubusercontent.com/jmnote/z-dataset/master/wikipedia.org/join-sql.sql | mysql wikipedia \
    && mysql -e 'CREATE DATABASE sample' \
    && curl -fsSL https://www.w3resource.com/sql/sample-database-of-sql-in-mysql-format.txt | mysql sample \
    && chown -R user01:user01 /var/run/mysqld/ /var/lib/mysql \
    && chmod -R a+rw /var/run/mysqld/ \
    && echo 'docker-entrypoint.sh mysqld > /tmp/log.txt 2>&1 &' >> /tmp/entrypoint.sh \
    && echo 'while ! mysqladmin ping --silent; do sleep 1; done' >> /tmp/entrypoint.sh \
    && echo 'mysql wikipedia -t -uroot < runbox.sql' >> /tmp/entrypoint.sh

USER user01
WORKDIR /home/user01/
