# main
FROM gradle:jdk21

RUN set -eux \
    && useradd -m -d /home/user01 user01 \
    && mkdir /demo \
    && chown -R user01:user01 /demo \
    && curl -LO https://github.com/JetBrains/kotlin/releases/download/v2.1.0/kotlin-compiler-2.1.0.zip \
    && unzip kotlin-compiler-2.1.0.zip -d /opt/ \
    && rm -f kotlin-compiler-2.1.0.zip

ENV PATH=$PATH:/opt/kotlinc/bin
USER user01
WORKDIR /demo
