FROM debian:12.8-slim

RUN set -eux \
    && useradd -m -d /home/user01 user01 \
    && echo 'deb http://ftp.debian.org/debian unstable main contrib non-free' > /etc/apt/sources.list.d/unstable.list \
    && apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    sqlite3 \
    time \
    && cd /home/user01/ \
    && curl -fsSL -o northwind.db https://raw.githubusercontent.com/jpwhite3/northwind-SQLite3/4f56e7f5906dfd23b25244c5bfe8fb5da6402efd/dist/northwind.db \
    && rm -rf /var/lib/apt/lists/* \
    && echo '.mode table' >> .sqliterc \
    && echo '.open northwind.db' >> .sqliterc

USER user01
WORKDIR /home/user01/
